### PR TITLE
Variant-Based Course Matching

### PR DESCRIPTION
**Pull request by deecewan**
Previously we just mapped over a big array of courses and compared to an image that looked like this:

iTerm2 svsr3u

The problem is that similarly named courses exist, like:
iTerm2 vRyy1c

and, in the grand scheme of that image, the difference in `DS` and `GBA` is quite small, so phash has a really tough time finding out which one is which.

The new algo, which I first implemented over in [`kart-rs`](https://github.com/deecewan/kart-rs), is slightly different. We split the big images above into 2. One for the "variant" text, like `DS` or `GBA`, and one for "the rest".

| Variant | Track Name |
|---------|------------|
| iTerm2 NjlbcF | iTerm2 5NDdep |
| iTerm2 Dlcdiv | iTerm2 c3rsBl |

This allows us to make `DS` significantly larger _in comparison_ to `GBA`, so we can filter down to only courses that have a `DS` variant. From there, we can match on "the rest" to figure out exactly which track it is.

This has the upside of being significantly more accurate than the original method. It has the downside of requiring _two_ p-hash calculations, but there are some other benefits:

- the old solution had to, worst case (and also best case lol), iterate through every single image in order to find the one we wanted. now, we iterate through 9 variants every time, and then only iterate through the images inside the variant. it's significantly shorter.
- we also no longer have to support the hacky "glob" thing that we used to have to distinguish between rainbow roads. because there's only (so far) 1 rainbow road per variant, we can just have 1 image (which reduces array allocations, and iterations)
- i also used the `threshold` function instead of just `black_threshold`. this sets all pixels to white or black, and eliminates the weird coloration of the text we had in some images
- also, deleted some of the reference images that we don't use anywhere (anymore?)

### CODE REVIEW

**Comment by xaviershay** [comment]
🤔 aesthetically we should probably have a benchmark script that can figure out average/worst/best case recognition times for our test images. _Should_ be straightforward? Shouldn't block this PR, just idle thinking for useful future work. (Also gives comparisons between this and `kart-rs`)

**Review by Jack-Kel — COMMENTED** [review]
Really smart approach 🧠 
I can approve it but might want to wait for one more reviewer 🤷

**Comment by deecewan** [comment]
@xaviershay are you looking for a "it takes this long to run the checker" type thing?

w.r.t `kart-rs`, there's no comparison to this. `kart-rs` is an order of magnitude (or more) faster. but you're right. it would be good to have actual numbers around it.

**Comment by deecewan** [comment]
also, the failing tests aren't true. they always fail. phashion doesn't install properly anymore.

**Comment by deecewan** [comment]
@xaviershay great work on benchmarking.

old: ~3s
new: ~5s

i need to make this better

**Comment by deecewan** [comment]
we don't really use this anymore, so i'm gonna close it

**Pull request closed without merging**
